#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 14, 2019 12:18:07 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import phone_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    phone_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    phone_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("310x300+570+252")
        top.title("Python Phone")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.032, rely=0.067, height=21, width=70)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(text='''ready''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.29, rely=0.067, relheight=0.08, relwidth=0.645)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=200)
        self.Text1.configure(wrap="word")

        self.ButtonHook = tk.Button(top)
        self.ButtonHook.place(relx=0.032, rely=0.2, height=230, width=65)
        self.ButtonHook.configure(activebackground="#f9f9f9")
        self.ButtonHook.configure(command=lambda: phone_support.buttonHookClickEvent(self, self.ButtonHook))
        self.ButtonHook.configure(text='''hook off''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.29, rely=0.2, height=50, width=60)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button2))
        self.Button2.configure(text='''1''')

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.516, rely=0.2, height=50, width=60)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button3))
        self.Button3.configure(text='''2''')

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.742, rely=0.2, height=50, width=60)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button4))
        self.Button4.configure(text='''3''')

        self.Button5 = tk.Button(top)
        self.Button5.place(relx=0.29, rely=0.4, height=50, width=60)
        self.Button5.configure(activebackground="#f9f9f9")
        self.Button5.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button5))
        self.Button5.configure(text='''4''')

        self.Button6 = tk.Button(top)
        self.Button6.place(relx=0.516, rely=0.4, height=50, width=60)
        self.Button6.configure(activebackground="#f9f9f9")
        self.Button6.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button6))
        self.Button6.configure(text='''5''')

        self.Button7 = tk.Button(top)
        self.Button7.place(relx=0.742, rely=0.4, height=50, width=60)
        self.Button7.configure(activebackground="#f9f9f9")
        self.Button7.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button7))
        self.Button7.configure(text='''6''')

        self.Button8 = tk.Button(top)
        self.Button8.place(relx=0.29, rely=0.6, height=50, width=60)
        self.Button8.configure(activebackground="#f9f9f9")
        self.Button8.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button8))
        self.Button8.configure(text='''7''')

        self.Button9 = tk.Button(top)
        self.Button9.place(relx=0.516, rely=0.6, height=50, width=60)
        self.Button9.configure(activebackground="#f9f9f9")
        self.Button9.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button9))
        self.Button9.configure(text='''8''')

        self.Button10 = tk.Button(top)
        self.Button10.place(relx=0.742, rely=0.6, height=50, width=60)
        self.Button10.configure(activebackground="#f9f9f9")
        self.Button10.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button10))
        self.Button10.configure(text='''9''')

        self.Button11 = tk.Button(top)
        self.Button11.place(relx=0.29, rely=0.8, height=50, width=60)
        self.Button11.configure(activebackground="#f9f9f9")
        self.Button11.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button11))
        self.Button11.configure(text='''#''')

        self.Button12 = tk.Button(top)
        self.Button12.place(relx=0.516, rely=0.8, height=50, width=60)
        self.Button12.configure(activebackground="#f9f9f9")
        self.Button12.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button12))
        self.Button12.configure(text='''0''')

        self.Button13 = tk.Button(top)
        self.Button13.place(relx=0.742, rely=0.8, height=50, width=60)
        self.Button13.configure(activebackground="#f9f9f9")
        self.Button13.configure(command=lambda: phone_support.buttonFieldClickEvent(self, self.Button13))
        self.Button13.configure(text='''*''')


if __name__ == '__main__':
    vp_start_gui()
