#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 14, 2019 12:18:11 PM CEST  platform: Linux

import sys

try:
    import Tkinter as tk
    from tkinter import *
except ImportError:
    import tkinter as tk
    from tkinter import *

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def buttonFieldClickEvent(p1, p2):
    p1.Text1.insert(END, p2['text'])
    sys.stdout.flush()


def buttonHookClickEvent(p1, p2):
    sys.stdout.flush()

    if p2['text'] == 'hook off':
        p2['text'] = 'hook on'
        p1.Label1['text'] = 'connected'
    else:
        p2['text'] = 'hook off'
        p1.Label1['text'] = 'ready'
        p1.Text1.delete(1.0, END)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import phone

    phone.vp_start_gui()
