#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 14, 2019 10:19:23 AM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 339x324+570+252
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Python Phone"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text ready 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex44 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 200 \
        -wrap word 
    .top42.tex44 configure -font "TkTextFont"
    .top42.tex44 insert end text
    vTcl:DefineAlias "$top.tex44" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text hook 
    vTcl:DefineAlias "$top.but46" "ButtonHook" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 1 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 2 
    vTcl:DefineAlias "$top.but48" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 3 
    vTcl:DefineAlias "$top.but49" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 4 
    vTcl:DefineAlias "$top.but50" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 5 
    vTcl:DefineAlias "$top.but51" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 6 
    vTcl:DefineAlias "$top.but52" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -state active -text 7 
    vTcl:DefineAlias "$top.but53" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 8 
    vTcl:DefineAlias "$top.but54" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 9 
    vTcl:DefineAlias "$top.but55" "Button10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {#} 
    vTcl:DefineAlias "$top.but56" "Button11" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text 0 
    vTcl:DefineAlias "$top.but57" "Button12" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text * 
    vTcl:DefineAlias "$top.but58" "Button13" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 20 -y 30 -width 70 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.tex44 \
        -in $top -x 100 -y 30 -width 200 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 20 -y 70 -width 65 -relwidth 0 -height 230 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 100 -y 70 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 170 -y 70 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 240 -y 70 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 100 -y 130 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 170 -y 130 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 240 -y 130 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 100 -y 190 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 170 -y 190 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 240 -y 190 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 100 -y 250 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 170 -y 250 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 240 -y 250 -width 60 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

